/**
 * Builds lib/beats.ts: a tiny per-track "beat map" (kick/onset strength every 20 ms) used by the music player
 * to pulse a soft LED behind it. Needs ffmpeg and the preview files in public/assets/audio.
 *
 *   node scripts/make-beats.mjs
 *
 * Re-run it whenever a preview file changes (the map follows the 30 s fragment, not the full song).
 */
import { spawnSync } from 'node:child_process';
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'public/assets/audio';
const RATE = 22050;
const HOP = 441; // 20 ms -> 50 fps
const FPS = RATE / HOP;

const pcm = (file, filter) => {
  const out = spawnSync('ffmpeg', ['-v', 'error', '-i', file, ...(filter ? ['-af', filter] : []), '-ac', '1', '-ar', String(RATE), '-f', 's16le', '-'], { maxBuffer: 1 << 28 }).stdout;
  return new Int16Array(out.buffer, out.byteOffset, Math.floor(out.length / 2));
};
const envelope = (s) => Array.from({ length: Math.floor(s.length / HOP) }, (_, i) => {
  let sum = 0;
  for (let j = i * HOP; j < (i + 1) * HOP; j++) sum += s[j] * s[j];
  return Math.sqrt(sum / HOP);
});
/** positive jump of the envelope over the average of the previous 8 frames */
const flux = (env) => env.map((v, i) => {
  const from = Math.max(0, i - 8);
  const avg = env.slice(from, i).reduce((a, b) => a + b, 0) / Math.max(1, i - from);
  return Math.max(0, v - avg);
});
const pct = (arr, p) => [...arr].sort((a, b) => a - b)[Math.floor(arr.length * p)] || 1;

const maps = {};
// The newest version of each preview wins: NN-slug-preview.mp3 < ...-preview-v2.mp3 < ...-preview-v3.mp3
const newest = {};
for (const n of readdirSync(DIR)) {
  const m = n.match(/^\d+-(.+?)-preview(?:-v(\d+))?\.mp3$/);
  if (!m) continue;
  const v = Number(m[2] || 1);
  if (!newest[m[1]] || v > newest[m[1]].v) newest[m[1]] = { v, f: n };
}
for (const [slug, { f }] of Object.entries(newest).sort(([a], [b]) => a.localeCompare(b))) {
  const file = join(DIR, f);
  const low = flux(envelope(pcm(file, 'lowpass=f=160')));
  const full = flux(envelope(pcm(file)));
  const lo = pct(low, 0.97), fu = pct(full, 0.97);
  const beat = low.map((v, i) => {
    const x = 0.75 * Math.min(1, v / lo) + 0.25 * Math.min(1, full[i] / fu);
    return Math.max(0, Math.min(1, (x - 0.18) / 0.82)); // gate: the LED rests between hits
  });
  maps[slug] = Buffer.from(Uint8Array.from(beat, (v) => Math.round(v * 255))).toString('base64');
  const peaks = beat.filter((v, i) => v > 0.5 && v >= (beat[i - 1] ?? 0) && v > (beat[i + 1] ?? 0)).length;
  console.log(slug.padEnd(18), `${beat.length} frames, ~${peaks} strong hits (${(peaks / (beat.length / FPS)).toFixed(1)}/s)`);
}

writeFileSync('lib/beats.ts', `// GENERATED by scripts/make-beats.mjs — do not edit by hand.
export const BEAT_FPS = ${FPS};

/** base64 of one byte (0-255 hit strength) per 20 ms of the 30 s preview, by track slug */
export const beatMaps: Record<string, string> = ${JSON.stringify(maps, null, 2)};
`);
